version: '3'

services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - app/warehouse_app/.env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
    depends_on:
      - web

  db:
    image: postgres
    env_file:
      - app/warehouse_app/.env

volumes:
  static_volume:
