"""Initial migration

Revision ID: 0bfa558c5f85
Revises: 
Create Date: 2023-12-13 12:43:04.981769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bfa558c5f85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution_picks_per_country_per_master_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_solution_profile_id', sa.Integer(), nullable=True),
    sa.Column('historic_result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['historic_result_id'], ['historicalresults.id'], ),
    sa.ForeignKeyConstraint(['warehouse_solution_profile_id'], ['warehouse_solution_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solution_picks_per_country_per_master_area_entrys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_picks_id', sa.Integer(), nullable=True),
    sa.Column('master_area', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('count_picks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['solution_picks_id'], ['solution_picks_per_country_per_master_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solution_picks_per_country_per_master_area_entrys')
    op.drop_table('solution_picks_per_country_per_master_area')
    # ### end Alembic commands ###
