# Use the official Redis image as a parent image
FROM redis:alpine

# (Optional) Copy custom configuration file if you have one
# COPY redis.conf /usr/local/etc/redis/redis.conf

# (Optional) Set command if you have a custom configuration
# CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
