{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Shipping window 1",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "WITH TotalPicks AS (\n  SELECT\n    SUM(count_picks) AS total\n  FROM\n    solution_picks_per_country_per_master_area_entrys\n  WHERE\n    master_area = 'm1'\n    AND solution_picks_id = 1\n    AND country IN ('CH', 'NO')\n)\nSELECT\n  spcmae.country,\n  spcmae.count_picks,\n  ROUND((spcmae.count_picks::DECIMAL / tp.total) * 100, 2) AS distribution\nFROM\n  solution_picks_per_country_per_master_area_entrys spcmae,\n  TotalPicks tp\nWHERE\n  spcmae.master_area = 'm1'\n  AND spcmae.solution_picks_id = 1\n  AND spcmae.country IN ('CH', 'NO');\n"
    }
   ]
  },
  {
   "title": "Shipping window 2",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH TotalPicks AS (\n  SELECT\n    SUM(count_picks) AS total\n  FROM\n    solution_picks_per_country_per_master_area_entrys\n  WHERE\n    master_area = 'm1'\n    AND solution_picks_id = 1\n    AND country IN ('GE')\n)\nSELECT\n  spcmae.country,\n  spcmae.count_picks,\n  ROUND((spcmae.count_picks::DECIMAL / tp.total) * 100, 2) AS distribution\nFROM\n  solution_picks_per_country_per_master_area_entrys spcmae,\n  TotalPicks tp\nWHERE\n  spcmae.master_area = 'm1'\n  AND spcmae.solution_picks_id = 1\n  AND spcmae.country IN ('GE');\n"
    }
   ]
  },
  {
   "title": "Shipping window 3",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "WITH TotalPicks AS (\n  SELECT\n    SUM(count_picks) AS total\n  FROM\n    solution_picks_per_country_per_master_area_entrys\n  WHERE\n    master_area = 'm1'\n    AND solution_picks_id = 1\n    AND country IN ('SW', 'FI')\n)\nSELECT\n  spcmae.country,\n  spcmae.count_picks,\n  ROUND((spcmae.count_picks::DECIMAL / tp.total) * 100, 2) AS distribution\nFROM\n  solution_picks_per_country_per_master_area_entrys spcmae,\n  TotalPicks tp\nWHERE\n  spcmae.master_area = 'm1'\n  AND spcmae.solution_picks_id = 1\n  AND spcmae.country IN ('SW', 'FI');\n"
    }
   ]
  },
  {
   "title": "Shipping window 3",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "WITH TotalPicks AS (\n  SELECT\n    SUM(count_picks) AS total\n  FROM\n    solution_picks_per_country_per_master_area_entrys\n  WHERE\n    master_area = 'm1'\n    AND solution_picks_id = 1\n    AND country IN ('NL', 'MT', 'UK', 'FR', 'BE', 'AU', 'SZ', 'DA', 'EI')\n)\nSELECT\n  spcmae.country,\n  spcmae.count_picks,\n  ROUND((spcmae.count_picks::DECIMAL / tp.total) * 100, 2) AS distribution\nFROM\n  solution_picks_per_country_per_master_area_entrys spcmae,\n  TotalPicks tp\nWHERE\n  spcmae.master_area = 'm1'\n  AND spcmae.solution_picks_id = 1\n  AND spcmae.country IN ('NL', 'MT', 'UK', 'FR', 'BE', 'AU', 'SZ', 'DA', 'EI');\n"
    }
   ]
  }
 ]
}