# Grafana/provisioning/datasources/default.yaml

apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
url: 92.68.232.34:5433
    user: postgres
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    database: postgres
    uid: b96049c8-1584-454c-a360-afb5de5c2320
    jsonData:
      tlsAuth: false
      tlsSkipVerify: true
      sslmode: disable # Corrected the sslmode configuration
      # Other parameters as needed
    isDefault: true
